### PR TITLE
return error if controller is being ran in an unsupported facility

### PR DESCRIPTION
**Pull request by ashleyschuett**
I'm not sure if this logic is correct. Since the facility ID can still be specified in the config file I'm thinking this should actually happen later with a check once the facility ID is assigned.

I wasn't sure if that is intentional or not though. Do you want people to be able to use storage in a different facility than the one their device is running in? 

If so I'll change this to get the facility and check it's features after the second `if config.FacilityID == "" ` check

### CODE REVIEW

**Comment by ashleyschuett** [comment]
If this, or my proposal is not how you would like this issue fixed I can close this PR.

**Comment by ntfrnzn** [comment]
This looks good, sorry for the delay.  I think the facilityID field in the config should (and will) be removed -- it's hard to justify a scenario where the controller is being run outside the facility.

**Comment by ashleyschuett** [comment]
Sorry, another bump for this. Should I close it?

**Comment by jacobsmith928** [comment]
@baldwinSPC @deitch can you review and help to close out?

**Comment by deitch** [comment]
@baldwinSPC can you review? I have been busy on ccm and am not fully up to date yet on CSI, prob not for another week or two. If not, comment here, and I will try to squeeze out some time next week.

**Comment by baldwinSPC** [comment]
@ntfrnzn ^^

**Pull request merged**
